apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: "{customer}"
    name: "{full_name}"
    subscriptionStart: "{sub_start}"
    custObjUuid: "{str_uuid}"
spec: 
  selector: 
    matchLabels: 
      customer: "{customer}"
      name: "{full_name}"
  template: 
    metadata:
      labels:
        customer: "{customer}"
        name: "{full_name}"
        subscriptionStart: "{sub_start}"
        custObjUuid: "{str_uuid}"
    spec:
      serviceAccountName: sa-server-pod
      securityContext:
        fsGroup: 1000
      containers:
        - name: "{full_name}"
          image: timche/csgo
          ports: 
            - containerPort: {dyn_port}
              protocol: TCP
            - containerPort: {dyn_port}
              protocol: UDP
          volumeMounts:
            - mountPath: /home/csgo/server
              name: csgo-data
          resources:
            limits:
              cpu: "1"
              memory: 2G
          env: {env_vars}
      volumes:
        - name: csgo-data
          persistentVolumeClaim:
            claimName: "csgo-base"

