apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: "{customer}"
    name: "{full_name}"
    subscriptionStart: "{sub_start}"
    custObjUuid: "{str_uuid}"
spec: 
  selector: 
    matchLabels: 
      customer: "{customer}"
      name: "{full_name}"
  template: 
    metadata:
      labels:
        customer: "{customer}"
        name: "{full_name}"
        subscriptionStart: "{sub_start}"
        custObjUuid: "{str_uuid}"
    spec:
      serviceAccountName: sa-server-pod
      containers:
        - name: "{full_name}"
          securityContext:
            fsGroup: 1000
          image: timche/csgo
          ports: 
            - containerPort: 27015
          env: {env_vars}
          volumeMounts:
            - mountPath: /home/csgo/server
              name: csgo-data
      volumes:
        - name: csgo-data
          persistentVolumeClaim:
            claimName: "pvc-{full_name}"

