apiVersion: apps/v1
kind: Deployment
metadata: 
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: "{customer}"
    name: "{full_name}"
    subscriptionStart: "{sub_start}"
    custObjUuid: "{str_uuid}"
spec: 
  selector: 
    matchLabels: 
      customer: "{customer}"
      name: "{full_name}"
  template: 
    metadata:
      labels:
        customer: "{customer}"
        name: "{full_name}"
        subscriptionStart: "{sub_start}"
        custObjUuid: "{str_uuid}"
    spec:
      containers:
        - name: "{full_name}"
          image: timche/csgo
          ports: 
            - containerPort: 27015
          env:
            - name: CSGO_GSLT
              valueFrom: 
                  secretKeyRef: 
                      name: "{secret_name}"
                      key: value
          volumeMounts:
            - mountPath: /home/csgo/server
              name: csgo-data
          resources:
            limits:
              memory: "1G"
              cpu: "4500m"
            requests:
              memory: "500m"
      securityContext:
        fsGroup: 1000
      volumes:
        - name: csgo-data
          persistentVolumeClaim:
            claimName: "pvc-{full_name}"

