apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: "{customer}"
    name: "{full_name}"
    subscriptionStart: "{sub_start}"
    custObjUuid: "{str_uuid}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi