apiVersion: v1
kind: Service
metadata: 
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: {customer}
    name: {full_name}
    subscriptionStart: {sub_start}
    custObjUuid: {str_uuid}
spec:
  selector:
    custObjUuid: "{str_uuid}"
  ports:
  - port: 27015
    protocol: TCP
    targetPort: "{dyn_port}"
  - port: 27015
    protocol: UDP
    targetPort: "{dyn_port}"
  type: LoadBalancer
