apiVersion: v1
kind: Service
metadata: 
  name: "{full_name}"
  namespace: "{namespace}"
  labels:
    customer: "{customer}"
    name: "{full_name}"
    subscriptionStart: "{sub_start}"
    custObjUuid: "{str_uuid}"
spec:
  selector:
    custObjUuid: "{str_uuid}"
  ports:
  - port: {dyn_port}
    name: csgo-tcp
    protocol: TCP
    targetPort: {dyn_port}
  - port: {dyn_port}
    name: csgo-udp
    protocol: UDP
    targetPort: {dyn_port}
  type: LoadBalancer
