apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prism-operator-crb
  namespace: prism-servers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prism-operator-cr
subjects:
  - kind: ServiceAccount
    name: sa-prism-operator
    namespace: prism-server