apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prismservers.prism-hosting.ch
spec:
  group: prism-hosting.ch
  scope: Namespaced
  names:
    plural: prismservers
    singular: prismserver
    kind: PrismServer
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            x-kubernetes-validations:
              - rule: "self.subscriptionStart <= 1000000000 || self.subscriptionStart >= 2147483647"
                message: "subscriptionStart is an invalid UNIX timestamp or not within an acceptable range."
            properties:
              customer:
                type: string
              subscriptionStart:
                type: integer
            required:
              - customer
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true