apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prismservers.prism-hosting.ch
spec:
  group: prism-hosting.ch
  names:
    plural: prismservers
    singular: prismserver
    kind: PrismServer
    listKind: PrismServerList
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - customer
                - env
              properties:
                customer:
                  type: string
                env:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - value
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                  x-kubernetes-validations:
                    - rule: "self.exists(e, e.name == 'CSGO_GSLT')"
                      message: Must specify env var 'CSGO_GSLT
                subscriptionStart:
                  type: integer
                  minimum: 0
                  maximum: 2147483647
              x-kubernetes-preserve-unknown-fields: true
              x-kubernetes-validations:
                - rule: oldSelf.customer == self.customer
                  message: Field 'customer' is immutable
                - rule: oldSelf.subscriptionStart == self.subscriptionStart
                  message: Field 'subscriptionStart' is immutable
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true