apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prismservers.prism-hosting.ch
spec:
  group: prism-hosting.ch
  scope: Namespaced
  names:
    plural: prismservers
    singular: prismserver
    kind: PrismServer
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              customer:
                type: string
              image:
                type: string
              subscriptionStart:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true