apiVersion: apps/v1
kind: Deployment
metadata:
  name: prismserver-operator
  namespace: prism-servers
  labels:
    operator: prism-servers
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prismserver-operator
  template:
    metadata:
      labels:
        app: prismserver-operator
    spec:
      serviceAccountName: sa-prism-operator
      containers:
      - name: prismserver-operator
        image: prismhosting/ocp-csgo-operator:latest
        imagePullPolicy: Always
        env:
          - name: UNIFI_API_HOST
            valueFrom:
              configMapKeyRef:
                key: unifi-api-host
                name: unifi-api-env
          - name: UNIFI_API_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: unifi-api-credentials
          - name: UNIFI_API_PASS
            valueFrom:
              secretKeyRef:
                key: password
                name: unifi-api-credentials