apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-csgo-pv
  namespace: prism-servers
spec:
  capacity:
    storage: 40G
  accessModes:
    - ReadWriteMany
  nfs:
    server: files.androme.da
    path: /csgo
  storageClassName: ""
