apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prism-operator
  namespace: prism-servers
subjects:
- kind: User
  name: sa-prism-operator
- kind: User
  name: sa-server-pod
roleRef:
  kind: Role
  name: prism-operator
  apiGroup: rbac.authorization.k8s.io