apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prism-operator
  namespace: prism-servers
rules:
- apiGroups: [apiextensions.k8s.io]
  resources: [customresourcedefinitions]
  verbs: [list, get]
- apiGroups: [zalando.org]
  resources: [clusterkopfpeerings]
  verbs: [list, watch, patch, get]
- apiGroups: [events.k8s.io]
  resources: [events]
  verbs: [create]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: [""]
  resources: [pods, deployments, services]
  verbs: [get, list, watch, create, update, patch, delete]
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list]
- apiGroups: ["apiextensions.k8s.io"]
  resources: [customresourcedefinitions]
  verbs: [watch, list]
- apiGroups: ["prism-hosting.ch"]
  resources: [prismservers]
  verbs: ["*"]