name: Build and deploy operator

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  pull_request:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  workflow_dispatch:

jobs:
  build:
    uses: Prism-Hosting/git-runner-builder-image/.github/workflows/docker-build.yml@main

  update_operator:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Login to cluster
      run: oc login ${{ secrets.OPENSHIFT_SERVER }} --token='${{ secrets.OPENSHIFT_SA_TOKEN }}' --insecure_skip_tls_verify=true

    - name: Remove operator pods
      run: oc -n ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} delete $(oc -n ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} get po -o name | grep operator)
      