name: Build and deploy operator

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  pull_request:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  workflow_dispatch:

jobs:
  docker-build:
    uses: Prism-Hosting/git-workflows/.github/workflows/docker-build.yml@main
    secrets: inherit

  update_operator:
    uses: Prism-Hosting/git-workflows/.github/workflows/oc-action.yml@main
    secrets: inherit
    needs: build
    with:
      namespace: ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} 
      oc-command: delete $(oc -n ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} get po -o name | grep operator)
      