name: Operator CI/CD

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  pull_request:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: thisisnttheway/prism-hosting
        tags: |
          # set latest tag for default branch
          type=raw,value=latest
          type=ref,event=branch
        
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
  
  update_operator:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: latest

    - name: Login to cluster
      run: oc login ${{ secrets.OPENSHIFT_SERVER }} --token='${{ secrets.OPENSHIFT_SA_TOKEN }}' --insecure_skip_tls_verify=true

    - name: Scale down operator deployment
      run: oc -n ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} delete $(oc -n ${{ vars.OPENSHIFT_PRISM_NAMESPACE }} get po -o name | grep operator)